[workspace]
members = [
    "gst-example",
    "plugin",
    "meta/example-c-sys",
    "meta/example-rs",
    "meta/example-rs-sys",
]

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
