name: Build and test
on:
  push:
    branches:
      - master
    paths:
      - gst-example
      - meta
      - plugin
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          version: 1.0
      - run: rustup toolchain install stable --profile minimal
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - run: mkdir artifacts
      - run: make -C plugin build TARGET=release
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: uzuna/go-bin-deb:latest
    defaults:
      run:
        shell: sh
    steps:
      - uses: actions/checkout@v3
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - run: mkdir artifacts
      - name: Download binaries
        id: download
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - run: ls -la
      - name: make deb package
        run: make -C plugin deb
      - name: Upload package
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: deb
