name: Build and test
on:
  push:
    branches:
      - 'master'
    paths:
      - gst-example
      - meta
      - plugin
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ github.workspace }}
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          version: 1.0
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          key: "build"
      - name: build
        run: make build
      - name: check format
        run: cargo fmt --all -- --check
      - name: check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test
        run: cargo test --all -- --nocapture
  deb:
    needs: build-test
    runs-on: ubuntu-latest
    container:
      image: uzuna/go-bin-deb:latest
      volumes:
        - ${{ github.workspace }}:/repo
    defaults:
      run:
        shell: sh
        working-directory: /repo
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ github.workspace }}
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: deb
        run: cd plugin && make deb
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: deb
          retention-days: 5
